### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by Trouble5** [irychen/super-admin#1]
请问启动是那个命令
`    "scripts": {
        "dev": "vite  --host ",
        "format": "prettier --write \"src/**/*.{ts,tsx}\" \"./*.{js,cjs,html,jsx,json,md,ts,tsx}\"",
        "build": "tsc && vite build",
        "build-analyze": "cross-env ANALYZE=true vite build",
        "build-gh": "cross-env BASE_SITE_URL=/super-admin/ vite build",
        "lint": "eslint src --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
        "preview": "vite preview",
        "prepare": "husky install"
    },`

**Comment by finedaybreak** [comment]
1. 全局安装 pnpm 包管理器  `npm install pnpm -g `
2. 安装依赖 `pnpm install`
3. 启动 `pnpm run dev`
